### ISSUE TITLE
signTransaction incompatible with TronWeb v6.0.0

### ISSUE THREAD

**Issue by trashpirate** [tronweb3/tronwallet-adapter#14]
It looks like that `signTransaction()` from useWallet is not compatible with the return type of `tronWeb.transactionBuilder.triggerSmartContract()` as of TronWeb version 6.0.0. 

The main issue seems to be the contract type defined in `transaction.raw_data` which is defined as a string, but TronWeb 6.0.0 uses `TriggerSmartContract` type. 

Thus, the Transaction type of tronwallet-adapter is incompatible with `Transaction<TriggerSmartContract>` and `SignedTransaction<ContractParamter>`.

Code showing with issue:

```
const parameter: any[] = [];
const options = {
    feeLimit: 100000000,
    callValue: 0,
    txLocal: true,

};

const { transaction } = await tronWeb.transactionBuilder.triggerSmartContract(NFT_CONTRACT, "mint()", options,
    parameter, address);

console.log("unsigned: ", transaction);

try {
    const signedTransaction = await signTransaction(transaction); // ERROR here because of type
    console.log("signed: ", signedTransaction);


    const receipt = await tronWeb.trx.sendRawTransaction(signedTransaction); // ERROR here because of type after converting the Transaction type manually
    
    ...
    }
```

Package.json:

```
"@tronweb3/tronwallet-abstract-adapter": "^1.1.7",
    "@tronweb3/tronwallet-adapter-react-hooks": "^1.1.8",
    "@tronweb3/tronwallet-adapter-react-ui": "^1.1.9",
    "@tronweb3/tronwallet-adapters": "^1.1.5",
    "next": "^14.2.14",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-hot-toast": "^2.4.1",
    "react-spinners": "^0.13.8",
    "tronweb": "^6.0.0",
    "viem": "^2.21.17",
    "@types/node": "^20.16.10",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.0",
    "eslint": "^8.57.1",
    "eslint-config-next": "14.2.3",
    "postcss": "^8.4.47",
    "tailwindcss": "^3.4.13",
    "typescript": "^5.6.2"
```

**Comment by way2ex** [comment]
Thanks a lot for your attention. We will update the types to be consistent  with TronWeb v6

**Comment by zorro11639** [comment]
Thanks a lot for your attention. We will update the types to be consistent with TronWeb v6

**Comment by zorro11639** [comment]
The latest version has replace the types with those from TronWeb v6. Please update the adapter version and it will work fine.

**Comment by trashpirate** [comment]
Amazing, thank you so much!
