### ISSUE TITLE
Error during connection or transaction execution: Invalid address provided

### ISSUE THREAD

**Issue by MiracleWeb3** [tronweb3/tronwallet-adapter#4]
while using @tronweb3/tronwallet-adapter-walletconnect I always have same error, no matter what code will I use. Simple code for modal and transaction of TRX looks like that:
![image](https://github.com/user-attachments/assets/6aa27b1a-d582-46f6-906d-21dfa1f02441)

and it still returns an error

![image](https://github.com/user-attachments/assets/752c7ebb-ea9e-4af2-8b58-bc6b05639e8e)

I don't know the way to solve it, so I'm asking for help here

**Comment by MiracleWeb3** [comment]
Despite the fact that I tried to ask gpt4 to solve that, I tried with default code from readme, and still got same error.

**Comment by MiracleWeb3** [comment]
Now tried with code from readme
![image](https://github.com/user-attachments/assets/90d3bf0b-8da8-4a0c-bb29-077805725c37)

Exactly same error, i'm lost

**Comment by zorro11639** [comment]
The error occurs because the invalid address is provided. Could you please add the code to verify whether the address is valid ?
```js
console.log(tronWeb.isAddress(targetAddress));
```

**Comment by MiracleWeb3** [comment]
> The error occurs because the invalid address is provided. Could you please add the code to verify whether the address is valid ?
> 
> ```js
> console.log(tronWeb.isAddress(targetAddress));
> ```

That was probably one of the first things that gpt4 said me to do, and error was still there, he also advised me to specify the data type definitions of all constants/variables that I enter, and I tried that one too. Error is still here. Its completely easy to reproduce, simple .html and demo code from readme as .js bundled with webpack or vite (they both give me the very same error).

**Comment by MiracleWeb3** [comment]
Like, it shows me modal of walletconnect, I connect my trust wallet to it, and then this error happens.
![image](https://github.com/user-attachments/assets/ea063ebb-2f79-4282-b2c4-159f03013bbf)
![image](https://github.com/user-attachments/assets/8ca8bbdf-1677-4b36-8bbe-871a8590b4f4)
And then boom, error is in console, nothing happens.

**Comment by zorro11639** [comment]
For now trust wallet does not support connecting tron by walletconnect.
